CREATE TABLE IF NOT EXISTS sep_languages (
    language_code varchar(2) not null unique primary key,
    language_name varchar(32) not null unique
);

INSERT INTO sep_languages VALUES ('AR', 'Arabic'),
                                 ('BE', 'Belarusian'),
                                 ('BG', 'Bulgarian'),
                                 ('BS', 'Bosnian'),
                                 ('CS', 'Czech'),
                                 ('CY', 'Welsh'),
                                 ('DA', 'Danish'),
                                 ('DE', 'German'),
                                 ('EL', 'Greek'),
                                 ('EN', 'English'),
                                 ('ES', 'Spanish'),
                                 ('ET', 'Estonian'),
                                 ('FA', 'Persian'),
                                 ('FI', 'Finnish'),
                                 ('FJ', 'Fijian'),
                                 ('FR', 'French'),
                                 ('GA', 'Irish'),
                                 ('HE', 'Hebrew'),
                                 ('HI', 'Hindi'),
                                 ('HR', 'Croatian'),
                                 ('HT', 'Haitian'),
                                 ('HU', 'Hungarian'),
                                 ('HY', 'Armenian'),
                                 ('ID', 'Indonesian'),
                                 ('IS', 'Icelandic'),
                                 ('IT', 'Italian'),
                                 ('JS', 'Japanese'),
                                 ('KO', 'Korean'),
                                 ('LB', 'Luxembourgish'),
                                 ('LT', 'Lithuanian'),
                                 ('LV', 'Latvian'),
                                 ('MN', 'Mongolian'),
                                 ('MT', 'Maltese'),
                                 ('MY', 'Burmese'),
                                 ('NL', 'Dutch'),
                                 ('NO', 'Norwegian'),
                                 ('NV', 'Navajo'),
                                 ('PL', 'Polish'),
                                 ('PT', 'Portuguese'),
                                 ('RO', 'Romanian'),
                                 ('RU', 'Russian'),
                                 ('SK', 'Slovak'),
                                 ('SQ', 'Albanian'),
                                 ('SR', 'Serbian'),
                                 ('SV', 'Swedish'),
                                 ('TH', 'Thai'),
                                 ('TR', 'Turkish'),
                                 ('UK', 'Ukrainian'),
                                 ('VI', 'Vietnamese'),
                                 ('ZH', 'Chinese');