CREATE TABLE IF NOT EXISTS sep_user_info (
    userinfo_id int not null auto_increment unique primary key,
    user_id int not null,
    user_fname varchar(32) not null,
    user_lname varchar(32) not null,
    user_gender varchar(6) not null,
    user_language varchar(2) not null,
    user_region varchar(16) not null,
    FOREIGN KEY (user_id) REFERENCES sep_users(user_id),
    FOREIGN KEY (user_language) REFERENCES sep_languages(language_code),
    FOREIGN KEY (user_region) REFERENCES sep_regions(region_code)
);

INSERT INTO sep_user_info (user_id, user_fname, user_lname, user_gender, user_language, user_region) VALUES
(1, 'Emma', 'Tall', 'female', 'EN', 'GB'),
(2, 'Jeffy', 'Kake', 'male', 'EN', 'GB'),
(3, 'Isaac', 'Walterson', 'male', 'EN', 'GB'),
(4, 'Bonny', 'Griffin', 'female', 'EN', 'GB'),
(5, 'Bill', 'NoGates', 'male', 'EN', 'GB'),
(6, 'Rebecca', 'Village', 'female', 'EN', 'GB'),
(7, 'Jacky', 'Kingsley', 'female', 'EN', 'GB'),
(8, 'Jonathan', 'Walker', 'male', 'EN', 'GB'),
(9, 'Josephine', 'Short', 'female', 'EN', 'GB'),
(10, 'Chan', 'Bailey', 'male', 'EN', 'GB'),
(11, 'Angel', 'Kake', 'female', 'EN', 'GB'),
(12, 'Arnold', 'Rufford', 'male', 'EN', 'GB'),
(13, 'Kate', 'Blankard', 'female', 'EN', 'GB'),
(14, 'Wayne', 'Ford', 'male', 'EN', 'GB'),
(15, 'Toleen', 'Stark', 'female', 'EN', 'GB'),
(16, 'Kong', 'King', 'male', 'EN', 'GB'),
(17, 'Diana', 'Prince', 'female', 'EN', 'GB'),
(18, 'Ben', 'Batty', 'male', 'EN', 'GB'),
(19, 'Sophie', 'Widow', 'female', 'EN', 'GB'),
(20, 'Brad', 'Litt', 'male', 'EN', 'GB'),
(21, 'Mila', 'Jonesvich', 'female', 'EN', 'GB'),
(22, 'Peter', 'Parked', 'male', 'EN', 'GB'),
(23, 'Mary', 'Lane', 'female', 'EN', 'GB'),
(24, 'Harry', 'Looter', 'male', 'EN', 'GB'),
(25, 'Maggie', 'Joeseen', 'female', 'EN', 'GB'),
(26, 'Harold', 'Mogwie', 'male', 'EN', 'GB'),
(27, 'Margot', 'Robert', 'female', 'EN', 'GB'),
(28, 'Robert', 'Jones', 'male', 'EN', 'GB'),
(29, 'Amy', 'Shoee', 'female', 'EN', 'GB'),
(30, 'John', 'Smith', 'male', 'EN', 'GB'),
(31, 'Jane', 'Smith', 'female', 'EN', 'GB'),
(32, 'Peter', 'Rick', 'male', 'EN', 'GB'),
(33, 'Handsome', 'Jack', 'male', 'EN', 'GB');