CREATE TABLE IF NOT EXISTS sep_user_info (
    userinfo_id int not null auto_increment unique primary key,
    user_id int not null unique ,
    user_fname varchar(32) not null,
    user_lname varchar(32) not null,
    user_gender varchar(6) not null,
    user_language varchar(2) not null,
    user_region varchar(16) not null,
    user_image TEXT default null,
    FOREIGN KEY (user_id) REFERENCES sep_users(user_id),
    FOREIGN KEY (user_language) REFERENCES sep_languages(language_code),
    FOREIGN KEY (user_region) REFERENCES sep_regions(region_code)
);

INSERT INTO sep_user_info (user_id, user_fname, user_lname, user_gender, user_language, user_region, user_image) VALUES
(1, 'Emma', 'Tall', 'female', 'EN', 'GB', 'user_1.jpg'),
(2, 'Jeffy', 'Kake', 'male', 'EN', 'GB', 'user_2.jpg'),
(3, 'Isaac', 'Walterson', 'male', 'EN', 'GB', 'user_3.jpg'),
(4, 'Bonny', 'Griffin', 'female', 'EN', 'GB', 'user_4.jpg'),
(5, 'Bill', 'NoGates', 'male', 'EN', 'GB', 'user_5.jpg'),
(6, 'Rebecca', 'Village', 'female', 'EN', 'GB', 'user_6.jpg'),
(7, 'Jacky', 'Kingsley', 'female', 'EN', 'GB', 'user_7.jpg'),
(8, 'Jonathan', 'Walker', 'male', 'EN', 'GB', 'user_8.jpg'),
(9, 'Josephine', 'Short', 'female', 'EN', 'GB', 'user_9.jpg'),
(10, 'Chan', 'Bailey', 'male', 'EN', 'GB', 'user_10.jpg'),
(11, 'Angel', 'Kake', 'female', 'EN', 'GB', 'user_11.jpg'),
(12, 'Arnold', 'Rufford', 'male', 'EN', 'GB', 'user_12.jpg'),
(13, 'Kate', 'Blankard', 'female', 'EN', 'GB', 'user_13.jpg'),
(14, 'Wayne', 'Ford', 'male', 'EN', 'GB', 'user_14.jpg'),
(15, 'Toleen', 'Stark', 'female', 'EN', 'GB', 'user_15.jpg'),
(16, 'Kong', 'King', 'male', 'EN', 'GB', null),
(17, 'Diana', 'Prince', 'female', 'EN', 'GB', 'user_17.jpg'),
(18, 'Ben', 'Batty', 'male', 'EN', 'GB', 'user_18.jpg'),
(19, 'Sophie', 'Widow', 'female', 'EN', 'GB', 'user_19.jpg'),
(20, 'Brad', 'Litt', 'male', 'EN', 'GB', null),
(21, 'Mila', 'Jonesvich', 'female', 'EN', 'GB', null),
(22, 'Peter', 'Parked', 'male', 'EN', 'GB', null),
(23, 'Mary', 'Lane', 'female', 'EN', 'GB', null),
(24, 'Harry', 'Looter', 'male', 'EN', 'GB', null),
(25, 'Maggie', 'Joeseen', 'female', 'EN', 'GB', null),
(26, 'Harold', 'Mogwie', 'male', 'EN', 'GB', null),
(27, 'Margot', 'Robert', 'female', 'EN', 'GB', null),
(28, 'Robert', 'Jones', 'male', 'EN', 'GB', null),
(29, 'Amy', 'Shoee', 'female', 'EN', 'GB', null),
(30, 'John', 'Smith', 'male', 'EN', 'GB', null),
(31, 'Jane', 'Smith', 'female', 'EN', 'GB', null),
(32, 'Peter', 'Rick', 'male', 'EN', 'GB', null),
(33, 'Handsome', 'Jack', 'male', 'EN', 'GB', null);