CREATE TABLE IF NOT EXISTS sep_jobs_list (
    job_code int(9) not null unique primary key,
    job_name varchar(64) not null
);

INSERT INTO sep_jobs_list VALUES 
(1, 'Developer'),
(2, 'Server Software Engineer'),
(3, 'Java Developer'),
(4, 'Software Engineer'),
(5, 'Web Developer'),
(6, 'Android Software Engineer'),
(7, 'Backend Software Engineer'),
(8, 'Frontend Software Engineer'),
(9, 'C Developer'),
(10, 'C++ Developer'),
(11, 'Python Developer'),
(12, 'PHP Developer'),
(13, 'Database Engineer'),
(14, 'Cloud Engineer'),
(15, 'iOS Software Engineer'),
(16, 'Full Stack Software Engineer'),
(17, 'Backend Developer'),
(18, 'Frontend Developer'),
(19, 'Full Stack Developer'),
(20, 'C# Developer'),
(21, 'Machine Learning'),
(22, 'Artifical Intelligence'),
(23, 'Games Developer'),
(24, 'OS Engineer'),
(25, 'OS Developer'),
(26, 'React Developer'),
(27, 'AngularJS Developer'),
(28, 'Ethical Hacking'),
(29, 'User Experience'),
(30, 'Data Science'),
(31, 'Cloud Developer'),
(32, 'Cloud Support'),
(33, 'DevOps'),
(34, 'Cybersecurity'),
(35, 'Wordpress'),
(36, 'Designer'),
(37, 'User Interface'),
(38, 'Product Designer'),
(39, 'Content Designer'),
(40, 'Data Designer'),
(41, 'Visual Designer'),
(42, 'Web Designer'),
(43, 'Game Designer'),
(44, 'Character Design'),
(45, 'Marketing'),
(46, 'Digital Marketing'),
(47, 'Marketing Specialist'),
(48, 'Marketing Analyst'),
(49, 'Marketing Manager'),
(50, 'Content Marketing'),
(51, 'Campaigns Manager'),
(52, 'Product Marketing'),
(53, 'Business Analyst'),
(54, 'Ad Specialist'),
(55, 'Advisor'),
(56, 'Social Media Manager'),
(57, 'Consulting'),
(58, 'Bookkeeper'),
(59, 'Trader'),
(60, 'Accountant'),
(61, 'Finance Analyst'),
(62, 'Tutoring'),
(63, 'Virtual Assistant'),
(64, 'Data Entry'),
(65, 'Proof Reader'),
(66, 'Reviewer'),
(67, 'Influencer'),
(68, 'World Dominator');