INSERT INTO sep_jobs_list VALUES (1, 'Software Engineer'),
                                 (2, 'Marketing'),
                                 (3, 'Designer'),
                                 (4, 'Artificial Intelligence'),
                                 (5, 'Web Development'),
                                 (6, 'Games Development'),
                                 (7, 'Tutor'),
                                 (8, 'Freelance Writer'),
                                 (9, 'Transcriptionist'),
                                 (10, 'Social Media Manager'),
                                 (11, 'Bookkeeper'),
                                 (12, 'Advisor'),
                                 (13, 'Virtual Assistant'),
                                 (14, 'Wordpress'),
                                 (15, 'Data Entry'),
                                 (16, 'Proof Reader'),
                                 (17, 'Reviewer'),
                                 (18, 'Influencer'),
                                 (19, 'Ad Specialist');