-- CREATE TABLE IF NOT EXISTS sep_users (
--     user_id int not null auto_increment unique primary key,
--     user_email varchar(128) not null unique,
--     user_password varchar(128) not null
-- );
--
-- DELETE FROM sep_users WHERE user_email ='user';
-- INSERT INTO sep_users (user_email, user_password) VALUES ('user', 'password');
--
-- CREATE TABLE IF NOT EXISTS sep_languages (
--     language_code varchar(2) not null unique primary key,
--     language_name varchar(32) not null unique
-- );
--
-- CREATE TABLE IF NOT EXISTS sep_regions (
--     region_code varchar(16) not null unique primary key,
--     region_name varchar(32) not null unique
-- );
--
-- CREATE TABLE IF NOT EXISTS sep_user_info (
--      userinfo_id int not null auto_increment unique primary key,
--      user_id int not null,
--      user_fname varchar(32) not null,
--      user_lname varchar(32) not null,
--      user_gender varchar(6) not null,
--      user_language varchar(2) not null,
--      user_region varchar(16) not null,
--      FOREIGN KEY (user_id) REFERENCES sep_users(user_id),
--      FOREIGN KEY (user_language) REFERENCES sep_languages(language_code),
--      FOREIGN KEY (user_region) REFERENCES sep_regions(region_code)
-- );
--
-- CREATE TABLE IF NOT EXISTS sep_jobs_list (
--     job_code int(9) not null unique primary key,
--     job_name varchar(64) not null
--     );
--
-- CREATE TABLE IF NOT EXISTS sep_users_interested_jobs (
--     user_id int not null,
--     job_code int(9) not null,
--     FOREIGN KEY (user_id) REFERENCES sep_users(user_id),
--     FOREIGN KEY (job_code) REFERENCES sep_jobs_list(job_code)
-- );